version: "3.9"

services:
  calendarAI_bot:
    build: ./bot
    container_name: whatsapp_bot
    env_file: ./bot/.env
    volumes:
      - ./bot:/usr/src/app 
      - /usr/src/app/node_modules
    depends_on:
      - calendarAI_api

  calendarAI_api:
    build: ./calendar_service
    container_name: calendarAI_api
    env_file: ./calendar_service/.env
    ports:
      - "8000:8000"
    volumes:
      - ./calendar_service:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: calendar_db
    environment:
      POSTGRES_USER: ${USERDB_CALENDARIA}
      POSTGRES_PASSWORD: ${PASSWORDDB_CALENDARIA}
      POSTGRES_DB: ${DATABASE__CALENDARIA}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d calendaria_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: